version: '3'
services:
  log_reader:
    build: .
    environment:
      - addr=0.0.0.0:80
      - log_dir=/log
      - suffix=log
    volumes:
      - ./test_log_files:/log
    ports:
      - 8082:80